#!/usr/bin/env ruby
# frozen_string_literal: true

require "digest"
require "fileutils"

root = File.expand_path("../..", __dir__)
output = File.join(root, "Sources/GiftUIFailureDiagnostics/GiftUIFixedDiagnosticBuffer.swift")
capacities = [0, 8, 16, 64].freeze

def branch(capacity)
  fields = (0...capacity).map do |index|
    "    private var record#{index}: GiftUIDiagnosticRecord = Self.placeholder"
  end
  writes = (0...capacity).map do |index|
    "        case #{index}: record#{index} = record"
  end
  reads = (0...capacity).map do |index|
    "        case #{index}: record#{index}"
  end

  <<~SWIFT
    public static let capacity: UInt8 = #{capacity}
    #{fields.join("\n")}

    private mutating func store(_ record: GiftUIDiagnosticRecord, at index: UInt8) {
        switch index {
    #{writes.join("\n")}
        default: break
        }
    }

    private func storedRecord(at index: UInt8) -> GiftUIDiagnosticRecord? {
        switch index {
    #{reads.join("\n")}
        default: nil
        }
    }
  SWIFT
end

source = <<~SWIFT
  // Generated by scripts/contracts/generate-spec-003-diagnostic-buffer.rb.
  // Input capacities: #{capacities.join(", ")}.
  // Generator SHA-256: #{Digest::SHA256.file(__FILE__).hexdigest}

  import GiftUIFailureCore

  #if (GIFTUI_DIAGNOSTICS_CAPACITY_ZERO && GIFTUI_DIAGNOSTICS_CAPACITY_8) || (GIFTUI_DIAGNOSTICS_CAPACITY_ZERO && GIFTUI_DIAGNOSTICS_CAPACITY_16) || (GIFTUI_DIAGNOSTICS_CAPACITY_ZERO && GIFTUI_DIAGNOSTICS_CAPACITY_64) || (GIFTUI_DIAGNOSTICS_CAPACITY_8 && GIFTUI_DIAGNOSTICS_CAPACITY_16) || (GIFTUI_DIAGNOSTICS_CAPACITY_8 && GIFTUI_DIAGNOSTICS_CAPACITY_64) || (GIFTUI_DIAGNOSTICS_CAPACITY_16 && GIFTUI_DIAGNOSTICS_CAPACITY_64)
  #error("select exactly one GiftUI diagnostic-buffer capacity")
  #endif

  public struct GiftUIFixedDiagnosticBuffer: GiftUIDiagnosticSink, Sendable {
      public private(set) var count: UInt8 = 0
      public private(set) var droppedRecordCount: UInt32 = 0

  #if GIFTUI_DIAGNOSTICS_CAPACITY_ZERO
  #{branch(0)}
  #elseif GIFTUI_DIAGNOSTICS_CAPACITY_8
  #{branch(8)}
  #elseif GIFTUI_DIAGNOSTICS_CAPACITY_16
  #{branch(16)}
  #else
  #{branch(64)}
  #endif

      public init() {}

      package init(droppedRecordCount: UInt32) {
          self.droppedRecordCount = droppedRecordCount
      }

      public mutating func consume(
          _ record: GiftUIDiagnosticRecord
      ) -> GiftUIDiagnosticSinkResult {
          guard count < Self.capacity else {
              if droppedRecordCount < .max {
                  droppedRecordCount += 1
              }
              return .saturated
          }
          store(record, at: count)
          count += 1
          return .accepted
      }

      public subscript(index: UInt8) -> GiftUIDiagnosticRecord? {
          guard index < count else { return nil }
          return storedRecord(at: index)
      }

      private static let placeholder = GiftUIDiagnosticRecord(
          kind: .operationalOutcome,
          severity: .debug,
          flags: 0,
          origin: .foundation,
          affectedScope: .operation,
          condition: 0
      )
  }
SWIFT

case ARGV
when []
  FileUtils.mkdir_p(File.dirname(output)) unless Dir.exist?(File.dirname(output))
  File.write(output, source)
when ["--check"]
  abort "generated diagnostic buffer is stale" unless File.exist?(output) && File.read(output) == source
else
  abort "usage: generate-spec-003-diagnostic-buffer.rb [--check]"
end
