CONFIG_GPIO=y
CONFIG_FPU=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_BUILD_OUTPUT_BIN=y
CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y
CONFIG_MAIN_STACK_SIZE=2048
