swift-entry-symbol=giftui_swift_display_application_run
required-symbol=GiftUIDisplayILI9341
required-symbol=GiftUIBackendRGB565
required-symbol=GiftUIRuntimeStatic
required-symbol=GiftUIInputADS7846
required-symbol=ThermostatModel.swift.obj
zero-heap=true
