public enum GiftUIFailureCoreLayoutProbe {
    @inline(never) public static func conditionIDSize() -> UInt32 { UInt32(MemoryLayout<GiftUIConditionID>.size) }
    @inline(never) public static func conditionIDStride() -> UInt32 { UInt32(MemoryLayout<GiftUIConditionID>.stride) }
    @inline(never) public static func conditionIDAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIConditionID>.alignment) }
    @inline(never) public static func failureOriginSize() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureOrigin>.size) }
    @inline(never) public static func failureOriginStride() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureOrigin>.stride) }
    @inline(never) public static func failureOriginAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureOrigin>.alignment) }
    @inline(never) public static func affectedScopeSize() -> UInt32 { UInt32(MemoryLayout<GiftUIAffectedScope>.size) }
    @inline(never) public static func affectedScopeStride() -> UInt32 { UInt32(MemoryLayout<GiftUIAffectedScope>.stride) }
    @inline(never) public static func affectedScopeAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIAffectedScope>.alignment) }
    @inline(never) public static func containmentSize() -> UInt32 { UInt32(MemoryLayout<GiftUIContainment>.size) }
    @inline(never) public static func containmentStride() -> UInt32 { UInt32(MemoryLayout<GiftUIContainment>.stride) }
    @inline(never) public static func containmentAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIContainment>.alignment) }
    @inline(never) public static func failureFactSize() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureFact>.size) }
    @inline(never) public static func failureFactStride() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureFact>.stride) }
    @inline(never) public static func failureFactAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureFact>.alignment) }
    @inline(never) public static func operationalKindSize() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalKind>.size) }
    @inline(never) public static func operationalKindStride() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalKind>.stride) }
    @inline(never) public static func operationalKindAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalKind>.alignment) }
    @inline(never) public static func operationalFactSize() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalFact>.size) }
    @inline(never) public static func operationalFactStride() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalFact>.stride) }
    @inline(never) public static func operationalFactAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalFact>.alignment) }
    @inline(never) public static func outcomeSize() -> UInt32 { UInt32(MemoryLayout<GiftUIOutcome<UInt32>>.size) }
    @inline(never) public static func outcomeStride() -> UInt32 { UInt32(MemoryLayout<GiftUIOutcome<UInt32>>.stride) }
    @inline(never) public static func outcomeAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIOutcome<UInt32>>.alignment) }
    @inline(never) public static func failureAnnotationSize() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureAnnotation>.size) }
    @inline(never) public static func failureAnnotationStride() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureAnnotation>.stride) }
    @inline(never) public static func failureAnnotationAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureAnnotation>.alignment) }
    @inline(never) public static func failureAnnotationsSize() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureAnnotations>.size) }
    @inline(never) public static func failureAnnotationsStride() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureAnnotations>.stride) }
    @inline(never) public static func failureAnnotationsAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIFailureAnnotations>.alignment) }
    @inline(never) public static func residualDispositionSize() -> UInt32 { UInt32(MemoryLayout<GiftUIResidualDisposition>.size) }
    @inline(never) public static func residualDispositionStride() -> UInt32 { UInt32(MemoryLayout<GiftUIResidualDisposition>.stride) }
    @inline(never) public static func residualDispositionAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIResidualDisposition>.alignment) }
    @inline(never) public static func allowedDispositionsSize() -> UInt32 { UInt32(MemoryLayout<GiftUIAllowedDispositions>.size) }
    @inline(never) public static func allowedDispositionsStride() -> UInt32 { UInt32(MemoryLayout<GiftUIAllowedDispositions>.stride) }
    @inline(never) public static func allowedDispositionsAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIAllowedDispositions>.alignment) }
    @inline(never) public static func residualPolicyInputSize() -> UInt32 { UInt32(MemoryLayout<GiftUIResidualPolicyInput<UInt32>>.size) }
    @inline(never) public static func residualPolicyInputStride() -> UInt32 { UInt32(MemoryLayout<GiftUIResidualPolicyInput<UInt32>>.stride) }
    @inline(never) public static func residualPolicyInputAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIResidualPolicyInput<UInt32>>.alignment) }
    @inline(never) public static func operationalHealthStateSize() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalHealthState>.size) }
    @inline(never) public static func operationalHealthStateStride() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalHealthState>.stride) }
    @inline(never) public static func operationalHealthStateAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalHealthState>.alignment) }
    @inline(never) public static func operationalHealthSize() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalHealth>.size) }
    @inline(never) public static func operationalHealthStride() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalHealth>.stride) }
    @inline(never) public static func operationalHealthAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIOperationalHealth>.alignment) }
    @inline(never) public static func diagnosticKindSize() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticKind>.size) }
    @inline(never) public static func diagnosticKindStride() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticKind>.stride) }
    @inline(never) public static func diagnosticKindAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticKind>.alignment) }
    @inline(never) public static func diagnosticSeveritySize() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSeverity>.size) }
    @inline(never) public static func diagnosticSeverityStride() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSeverity>.stride) }
    @inline(never) public static func diagnosticSeverityAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSeverity>.alignment) }
    @inline(never) public static func diagnosticSelectionSize() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSelection>.size) }
    @inline(never) public static func diagnosticSelectionStride() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSelection>.stride) }
    @inline(never) public static func diagnosticSelectionAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSelection>.alignment) }
    @inline(never) public static func diagnosticRecordSize() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticRecord>.size) }
    @inline(never) public static func diagnosticRecordStride() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticRecord>.stride) }
    @inline(never) public static func diagnosticRecordAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticRecord>.alignment) }
    @inline(never) public static func diagnosticSinkResultSize() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSinkResult>.size) }
    @inline(never) public static func diagnosticSinkResultStride() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSinkResult>.stride) }
    @inline(never) public static func diagnosticSinkResultAlignment() -> UInt32 { UInt32(MemoryLayout<GiftUIDiagnosticSinkResult>.alignment) }
}
