CONFIG_FPU=y
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y
CONFIG_MAIN_STACK_SIZE=24576
CONFIG_HEAP_MEM_POOL_SIZE=0
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
CONFIG_MULTITHREADING=n
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_BOOT_BANNER=n
CONFIG_LOG=n
