// Generated by scripts/contracts/generate-spec-003-diagnostic-buffer.rb.
// Input capacities: 0, 8, 16, 64.
// Generator SHA-256: 231564aee958cac9f647d7efdde738f6caafd1d056933bbf90b76466a8fd87d8

import GiftUIFailureCore

#if (GIFTUI_DIAGNOSTICS_CAPACITY_ZERO && GIFTUI_DIAGNOSTICS_CAPACITY_8) || (GIFTUI_DIAGNOSTICS_CAPACITY_ZERO && GIFTUI_DIAGNOSTICS_CAPACITY_16) || (GIFTUI_DIAGNOSTICS_CAPACITY_ZERO && GIFTUI_DIAGNOSTICS_CAPACITY_64) || (GIFTUI_DIAGNOSTICS_CAPACITY_8 && GIFTUI_DIAGNOSTICS_CAPACITY_16) || (GIFTUI_DIAGNOSTICS_CAPACITY_8 && GIFTUI_DIAGNOSTICS_CAPACITY_64) || (GIFTUI_DIAGNOSTICS_CAPACITY_16 && GIFTUI_DIAGNOSTICS_CAPACITY_64)
#error("select exactly one GiftUI diagnostic-buffer capacity")
#endif

public struct GiftUIFixedDiagnosticBuffer: GiftUIDiagnosticSink, Sendable {
    public private(set) var count: UInt8 = 0
    public private(set) var droppedRecordCount: UInt32 = 0

#if GIFTUI_DIAGNOSTICS_CAPACITY_ZERO
public static let capacity: UInt8 = 0


private mutating func store(_ record: GiftUIDiagnosticRecord, at index: UInt8) {
    switch index {

    default: break
    }
}

private func storedRecord(at index: UInt8) -> GiftUIDiagnosticRecord? {
    switch index {

    default: nil
    }
}

#elseif GIFTUI_DIAGNOSTICS_CAPACITY_8
public static let capacity: UInt8 = 8
    private var record0: GiftUIDiagnosticRecord = Self.placeholder
    private var record1: GiftUIDiagnosticRecord = Self.placeholder
    private var record2: GiftUIDiagnosticRecord = Self.placeholder
    private var record3: GiftUIDiagnosticRecord = Self.placeholder
    private var record4: GiftUIDiagnosticRecord = Self.placeholder
    private var record5: GiftUIDiagnosticRecord = Self.placeholder
    private var record6: GiftUIDiagnosticRecord = Self.placeholder
    private var record7: GiftUIDiagnosticRecord = Self.placeholder

private mutating func store(_ record: GiftUIDiagnosticRecord, at index: UInt8) {
    switch index {
        case 0: record0 = record
        case 1: record1 = record
        case 2: record2 = record
        case 3: record3 = record
        case 4: record4 = record
        case 5: record5 = record
        case 6: record6 = record
        case 7: record7 = record
    default: break
    }
}

private func storedRecord(at index: UInt8) -> GiftUIDiagnosticRecord? {
    switch index {
        case 0: record0
        case 1: record1
        case 2: record2
        case 3: record3
        case 4: record4
        case 5: record5
        case 6: record6
        case 7: record7
    default: nil
    }
}

#elseif GIFTUI_DIAGNOSTICS_CAPACITY_16
public static let capacity: UInt8 = 16
    private var record0: GiftUIDiagnosticRecord = Self.placeholder
    private var record1: GiftUIDiagnosticRecord = Self.placeholder
    private var record2: GiftUIDiagnosticRecord = Self.placeholder
    private var record3: GiftUIDiagnosticRecord = Self.placeholder
    private var record4: GiftUIDiagnosticRecord = Self.placeholder
    private var record5: GiftUIDiagnosticRecord = Self.placeholder
    private var record6: GiftUIDiagnosticRecord = Self.placeholder
    private var record7: GiftUIDiagnosticRecord = Self.placeholder
    private var record8: GiftUIDiagnosticRecord = Self.placeholder
    private var record9: GiftUIDiagnosticRecord = Self.placeholder
    private var record10: GiftUIDiagnosticRecord = Self.placeholder
    private var record11: GiftUIDiagnosticRecord = Self.placeholder
    private var record12: GiftUIDiagnosticRecord = Self.placeholder
    private var record13: GiftUIDiagnosticRecord = Self.placeholder
    private var record14: GiftUIDiagnosticRecord = Self.placeholder
    private var record15: GiftUIDiagnosticRecord = Self.placeholder

private mutating func store(_ record: GiftUIDiagnosticRecord, at index: UInt8) {
    switch index {
        case 0: record0 = record
        case 1: record1 = record
        case 2: record2 = record
        case 3: record3 = record
        case 4: record4 = record
        case 5: record5 = record
        case 6: record6 = record
        case 7: record7 = record
        case 8: record8 = record
        case 9: record9 = record
        case 10: record10 = record
        case 11: record11 = record
        case 12: record12 = record
        case 13: record13 = record
        case 14: record14 = record
        case 15: record15 = record
    default: break
    }
}

private func storedRecord(at index: UInt8) -> GiftUIDiagnosticRecord? {
    switch index {
        case 0: record0
        case 1: record1
        case 2: record2
        case 3: record3
        case 4: record4
        case 5: record5
        case 6: record6
        case 7: record7
        case 8: record8
        case 9: record9
        case 10: record10
        case 11: record11
        case 12: record12
        case 13: record13
        case 14: record14
        case 15: record15
    default: nil
    }
}

#else
public static let capacity: UInt8 = 64
    private var record0: GiftUIDiagnosticRecord = Self.placeholder
    private var record1: GiftUIDiagnosticRecord = Self.placeholder
    private var record2: GiftUIDiagnosticRecord = Self.placeholder
    private var record3: GiftUIDiagnosticRecord = Self.placeholder
    private var record4: GiftUIDiagnosticRecord = Self.placeholder
    private var record5: GiftUIDiagnosticRecord = Self.placeholder
    private var record6: GiftUIDiagnosticRecord = Self.placeholder
    private var record7: GiftUIDiagnosticRecord = Self.placeholder
    private var record8: GiftUIDiagnosticRecord = Self.placeholder
    private var record9: GiftUIDiagnosticRecord = Self.placeholder
    private var record10: GiftUIDiagnosticRecord = Self.placeholder
    private var record11: GiftUIDiagnosticRecord = Self.placeholder
    private var record12: GiftUIDiagnosticRecord = Self.placeholder
    private var record13: GiftUIDiagnosticRecord = Self.placeholder
    private var record14: GiftUIDiagnosticRecord = Self.placeholder
    private var record15: GiftUIDiagnosticRecord = Self.placeholder
    private var record16: GiftUIDiagnosticRecord = Self.placeholder
    private var record17: GiftUIDiagnosticRecord = Self.placeholder
    private var record18: GiftUIDiagnosticRecord = Self.placeholder
    private var record19: GiftUIDiagnosticRecord = Self.placeholder
    private var record20: GiftUIDiagnosticRecord = Self.placeholder
    private var record21: GiftUIDiagnosticRecord = Self.placeholder
    private var record22: GiftUIDiagnosticRecord = Self.placeholder
    private var record23: GiftUIDiagnosticRecord = Self.placeholder
    private var record24: GiftUIDiagnosticRecord = Self.placeholder
    private var record25: GiftUIDiagnosticRecord = Self.placeholder
    private var record26: GiftUIDiagnosticRecord = Self.placeholder
    private var record27: GiftUIDiagnosticRecord = Self.placeholder
    private var record28: GiftUIDiagnosticRecord = Self.placeholder
    private var record29: GiftUIDiagnosticRecord = Self.placeholder
    private var record30: GiftUIDiagnosticRecord = Self.placeholder
    private var record31: GiftUIDiagnosticRecord = Self.placeholder
    private var record32: GiftUIDiagnosticRecord = Self.placeholder
    private var record33: GiftUIDiagnosticRecord = Self.placeholder
    private var record34: GiftUIDiagnosticRecord = Self.placeholder
    private var record35: GiftUIDiagnosticRecord = Self.placeholder
    private var record36: GiftUIDiagnosticRecord = Self.placeholder
    private var record37: GiftUIDiagnosticRecord = Self.placeholder
    private var record38: GiftUIDiagnosticRecord = Self.placeholder
    private var record39: GiftUIDiagnosticRecord = Self.placeholder
    private var record40: GiftUIDiagnosticRecord = Self.placeholder
    private var record41: GiftUIDiagnosticRecord = Self.placeholder
    private var record42: GiftUIDiagnosticRecord = Self.placeholder
    private var record43: GiftUIDiagnosticRecord = Self.placeholder
    private var record44: GiftUIDiagnosticRecord = Self.placeholder
    private var record45: GiftUIDiagnosticRecord = Self.placeholder
    private var record46: GiftUIDiagnosticRecord = Self.placeholder
    private var record47: GiftUIDiagnosticRecord = Self.placeholder
    private var record48: GiftUIDiagnosticRecord = Self.placeholder
    private var record49: GiftUIDiagnosticRecord = Self.placeholder
    private var record50: GiftUIDiagnosticRecord = Self.placeholder
    private var record51: GiftUIDiagnosticRecord = Self.placeholder
    private var record52: GiftUIDiagnosticRecord = Self.placeholder
    private var record53: GiftUIDiagnosticRecord = Self.placeholder
    private var record54: GiftUIDiagnosticRecord = Self.placeholder
    private var record55: GiftUIDiagnosticRecord = Self.placeholder
    private var record56: GiftUIDiagnosticRecord = Self.placeholder
    private var record57: GiftUIDiagnosticRecord = Self.placeholder
    private var record58: GiftUIDiagnosticRecord = Self.placeholder
    private var record59: GiftUIDiagnosticRecord = Self.placeholder
    private var record60: GiftUIDiagnosticRecord = Self.placeholder
    private var record61: GiftUIDiagnosticRecord = Self.placeholder
    private var record62: GiftUIDiagnosticRecord = Self.placeholder
    private var record63: GiftUIDiagnosticRecord = Self.placeholder

private mutating func store(_ record: GiftUIDiagnosticRecord, at index: UInt8) {
    switch index {
        case 0: record0 = record
        case 1: record1 = record
        case 2: record2 = record
        case 3: record3 = record
        case 4: record4 = record
        case 5: record5 = record
        case 6: record6 = record
        case 7: record7 = record
        case 8: record8 = record
        case 9: record9 = record
        case 10: record10 = record
        case 11: record11 = record
        case 12: record12 = record
        case 13: record13 = record
        case 14: record14 = record
        case 15: record15 = record
        case 16: record16 = record
        case 17: record17 = record
        case 18: record18 = record
        case 19: record19 = record
        case 20: record20 = record
        case 21: record21 = record
        case 22: record22 = record
        case 23: record23 = record
        case 24: record24 = record
        case 25: record25 = record
        case 26: record26 = record
        case 27: record27 = record
        case 28: record28 = record
        case 29: record29 = record
        case 30: record30 = record
        case 31: record31 = record
        case 32: record32 = record
        case 33: record33 = record
        case 34: record34 = record
        case 35: record35 = record
        case 36: record36 = record
        case 37: record37 = record
        case 38: record38 = record
        case 39: record39 = record
        case 40: record40 = record
        case 41: record41 = record
        case 42: record42 = record
        case 43: record43 = record
        case 44: record44 = record
        case 45: record45 = record
        case 46: record46 = record
        case 47: record47 = record
        case 48: record48 = record
        case 49: record49 = record
        case 50: record50 = record
        case 51: record51 = record
        case 52: record52 = record
        case 53: record53 = record
        case 54: record54 = record
        case 55: record55 = record
        case 56: record56 = record
        case 57: record57 = record
        case 58: record58 = record
        case 59: record59 = record
        case 60: record60 = record
        case 61: record61 = record
        case 62: record62 = record
        case 63: record63 = record
    default: break
    }
}

private func storedRecord(at index: UInt8) -> GiftUIDiagnosticRecord? {
    switch index {
        case 0: record0
        case 1: record1
        case 2: record2
        case 3: record3
        case 4: record4
        case 5: record5
        case 6: record6
        case 7: record7
        case 8: record8
        case 9: record9
        case 10: record10
        case 11: record11
        case 12: record12
        case 13: record13
        case 14: record14
        case 15: record15
        case 16: record16
        case 17: record17
        case 18: record18
        case 19: record19
        case 20: record20
        case 21: record21
        case 22: record22
        case 23: record23
        case 24: record24
        case 25: record25
        case 26: record26
        case 27: record27
        case 28: record28
        case 29: record29
        case 30: record30
        case 31: record31
        case 32: record32
        case 33: record33
        case 34: record34
        case 35: record35
        case 36: record36
        case 37: record37
        case 38: record38
        case 39: record39
        case 40: record40
        case 41: record41
        case 42: record42
        case 43: record43
        case 44: record44
        case 45: record45
        case 46: record46
        case 47: record47
        case 48: record48
        case 49: record49
        case 50: record50
        case 51: record51
        case 52: record52
        case 53: record53
        case 54: record54
        case 55: record55
        case 56: record56
        case 57: record57
        case 58: record58
        case 59: record59
        case 60: record60
        case 61: record61
        case 62: record62
        case 63: record63
    default: nil
    }
}

#endif

    public init() {}

    package init(droppedRecordCount: UInt32) {
        self.droppedRecordCount = droppedRecordCount
    }

    public mutating func consume(
        _ record: GiftUIDiagnosticRecord
    ) -> GiftUIDiagnosticSinkResult {
        guard count < Self.capacity else {
            if droppedRecordCount < .max {
                droppedRecordCount += 1
            }
            return .saturated
        }
        store(record, at: count)
        count += 1
        return .accepted
    }

    public subscript(index: UInt8) -> GiftUIDiagnosticRecord? {
        guard index < count else { return nil }
        return storedRecord(at: index)
    }

    private static let placeholder = GiftUIDiagnosticRecord(
        kind: .operationalOutcome,
        severity: .debug,
        flags: 0,
        origin: .foundation,
        affectedScope: .operation,
        condition: 0
    )
}
